baseURL                          = "https://scottkirk.dev/" # Your domain name. Must end with "/"
DefaultContentLanguage           = "en"                     # Default language for multilingual sites

[markup.goldmark.renderer]
  unsafe= true

[params]
    themeStyle                   = "light"                 # Choose "light" or "dark"
    favicon                      = "/img/fav.ico"          # Path to favicon file
    showRSSButton                = false                   # Show rss button in navigation
    fadeIn                       = true                    # Turn on/off the fade-in effect
    fadeInIndex                  = true                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "Jan 2, 2006"
    email                        = "scottkirk@scottkirk.dev" # E-mail address for contact section
    # customCSS                    = ["foo.css"]             # Include custom css files placed under assets/

    # Configure the home page
    [params.home]
        introHeight              = "fullheight"            # Input either "medium" or "large" or "fullheight"
        showLatest               = true                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        numberOfProjectsToShow   = 3                       # Maximum number of projects to show on home page. Unset or comment out to show all projects

    [params.projects]
        useTwoColumns            = false                   # Use a layout with two columns instead of three

    # Share buttons on blog post pages
    [params.share]
        twitter                  = true
        facebook                 = true
        googlePlus               = true
        pinterest                = true

    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
    [[params.social]]
        url   = "https://www.linkedin.com/in/scottrkirkpatrick/"
        icon  = "linkedin-in"
        icon_pack = "fab"
    [[params.social]]
        url   = "https://github.com/scott-kirk/"
        icon  = "github"
        icon_pack = "fab"
    [[params.social]]
        url   = "https://gitlab.com/scott-kirk/"
        icon  = "gitlab"
        icon_pack = "fab"
    [[params.social]]
        url = "mailto:scottkirk@scottkirk.dev"
        icon = "paper-plane"
        icon_pack = "fas"


# If you don't want to use the default menu, you can define one by yourself
# [[menu.main]]
#     name    = "Home"
#     url     = "/"
#     weight  = 0
# [[menu.main]]
#     name    = "Blog"
#     url     = "/blog/"
#     weight  = 1

# We only use tag as a taxonomies
# You can add more by yourself
[taxonomies]
  tag = "tags"

[languages]
    [languages.en]
        languageName     = "English"
        languageCode     = "en-us"
        contentDir       = "content/en"
        weight           = 0
        title            = "Scott Kirkpatrick"
        [languages.en.params]
            description  = "My adventures in software development"   # Max 160 characters show in search results
            # footerText   = ""                      # Text to override default footer text (markdown allowed)

